on: push
permissions:
    contents: write
jobs:
    h:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
        - env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - uses: actions/checkout@main
          with:
              ref: ${{ github.ref }}
        - run: ls -l main.m4.c
        - run: clang --version
        - run: for h in $(find -name '*.h');do m4 -D__h__="$h" $(find -name main.m4.c) | clang -x c - ; stat a.out >/dev/null && rm a.out ;done
