on: push
permissions:
    contents: write
jobs:
    h:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_CONTEXT: ${{ toJson(github) }}
        steps:
        - env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - uses: actions/checkout@main
          with:
              ref: ${{ github.ref }}
        - run: ls -l main.m4.c
        - run: ninja --version
